"""address model

Revision ID: 66239ac46309
Revises:
Create Date: 2019-05-22 21:22:58.153379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66239ac46309'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('address', sa.String(length=140), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('report_folder', sa.String(length=140), nullable=True),
        sa.Column('address_folder', sa.String(length=140), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_address'), 'address', ['address'], unique=False)
    op.create_index(op.f('ix_address_date'), 'address', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_date'), table_name='address')
    op.drop_index(op.f('ix_address_address'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
