"""init migration

Revision ID: cbb2054b549f
Revises: 
Create Date: 2019-05-25 10:27:25.304294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb2054b549f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=140), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('report_folder', sa.String(length=140), nullable=True),
    sa.Column('address_folder', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_address'), 'address', ['address'], unique=True)
    op.create_index(op.f('ix_address_date'), 'address', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_date'), table_name='address')
    op.drop_index(op.f('ix_address_address'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
